[project]
name = "pydeps-size"
version = "0.1.0"
description = "A package that tells you the size of your dependencies in Megabytes!"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ruff>=0.11.12",
]
